name: Release
on: 
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release channel'     
        required: true
        default: 'release'
jobs:
  release:
    runs-on: self-hosted
    permissions: 
      contents: read
      packages: write 
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
      - 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      -
        name: Generate changelog
        uses: FabricMC/fabric-action-scripts@v1
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - 
        name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - 
        name: Build and publish package
        run: ./gradlew build publish github --stacktrace
        env:
          RELEASE_CHANNEL: ${{ github.event.inputs.channel }}
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      -
        name: Send a Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}